### ISSUE TITLE
Add missing package in doc's example program

### ISSUE THREAD

**Issue by pravj** [Bowery/progress#1]
Hey @sjkaliski,

A nice tool. :zap: 

I tried running the program directly that you have written in the `doc.go` file but it was giving this error.

``` go
# command-line-arguments
./pro.go:16: undefined: url
```

This is because the example program missed importing the `net/url` package.

So, you should add it in the list there.

**Comment by larzconwell** [comment]
Hi @pravj. I've fixed it now, thanks!
